<?php

namespace App\Support\Filters\Listings;

use App\Models\Brand;
use App\Models\Listing;
use App\Support\Filters\Filter;
use Illuminate\Contracts\Pagination\Paginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;

class BrandFilter extends Filter
{
    protected $model = Brand::class;
    protected $baseModel = Listing::class;
    protected $relation = 'brand';
    protected $inverseRelation = 'listings';
    protected $name = 'brand';
    protected $value = null;

    public function setValue($value)
    {
        return parent::setValue((int)$value); // TODO: Change the autogenerated stub
    }

    public function filterQuery(Builder $query)
    {
        if ($this->isActive) {
            $query->where('brand_id', (int)$this->value);
        }
    }

    public function getOptions($possibilitiesQuery)
    {
        return [];
    }

    public function appendToPaginator(Paginator $paginator)
    {
        if (!empty($this->value)) {
            $paginator->appends('brand', $this->value);
        }
    }
}
