<?php

namespace App\Support\Filters\Listings;

use App\Http\Controllers\GetsDenormalizedProductCategories;
use App\Models\Listing;
use App\ProductCategory;
use App\Support\Filters\Filter;
use Illuminate\Contracts\Pagination\Paginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;
use Wax\Core\Filters\FilterOption;

class CategoryFilter extends Filter
{
    use GetsDenormalizedProductCategories;

    protected $model = ProductCategory::class;
    protected $baseModel = Listing::class;
    protected $relation = 'categories';
    protected $inverseRelation = 'listings';
    protected $name = 'category';
    protected $value = null;

    public function setValue($value)
    {
        return parent::setValue((int)$value); // TODO: Change the autogenerated stub
    }

    public function filterQuery(Builder $query)
    {
        if ($this->isActive) {
            $query->whereHas('categories', function ($query) {
                $query->where('product_categories.id', $this->value);
            });
        }
    }

    public function getOptions($possibilitiesQuery)
    {
        $possibilities = $possibilitiesQuery->pluck('id');
        $level = 0;
        $level1Category = null;
        $level2Category = null;
        $level3Category = null;
        if (! empty($this->value)) {
            $theCategory = ProductCategory::with('parent.parent')->find($this->value);
            if ($theCategory) {
                $level = 1;
                $level1Category = $theCategory;

                if ($level1Category->parent) {
                    $level = 2;
                    $level2Category = $level1Category;
                    $level1Category = $level2Category->parent;

                    if ($level1Category->parent) {
                        $level = 3;
                        $level3Category = $level2Category;
                        $level2Category = $level3Category->parent;
                        $level1Category = $level2Category->parent;
                    }
                }
            }
        }

        return ProductCategory::with([
                'listings',
                'children.listings',
                'children.children.listings'
            ])
            ->top()
            ->when($level > 0, function ($query) use ($level1Category) {
                return $query->where('id', $level1Category->id);
            })
            ->get()
            ->map(function ($category) use ($possibilities, $level, $level2Category) {
                $possibilitiesCount = $category->listings->pluck('id')->intersect($possibilities)->count();
                $extras = [
                    'count' => $possibilitiesCount,
                ];
                if ($level > 0) {
                    $extras['children'] = $category
                        ->children
                        ->when($level > 1, function ($query) use ($level2Category) {
                            return $query->where('id', $level2Category->id);
                        })
                        ->map(function ($category) use ($possibilities, $level) {
                            $possibilitiesCount = $category->listings->pluck('id')->intersect($possibilities)->count();
                            $extras = [
                                'count' => $possibilitiesCount,
                            ];
                            if ($level > 1) {
                                $extras['children'] = $category
                                    ->children
                                    ->map(function ($category) use ($possibilities) {
                                        $possibilitiesCount = $category->listings->pluck('id')->intersect($possibilities)->count();
                                        return new FilterOption(
                                            $category->name,
                                            $category->id,
                                            [
                                                'count' => $possibilitiesCount,
                                            ],
                                            $possibilitiesCount > 0,
                                            $category->id === $this->value
                                        );
                                    });
                            }
                            return new FilterOption(
                                $category->name,
                                $category->id,
                                $extras,
                                $category->listings->pluck('id')->intersect($possibilities)->count() > 0,
                                $category->id === $this->value
                            );
                        });
                }
                $option = new FilterOption(
                    $category->name,
                    $category->id,
                    $extras,
                    $possibilitiesCount > 0,
                    $category->id === $this->value
                );

                return $option;
            });
    }

    public function appendToPaginator(Paginator $paginator)
    {
        if (!empty($this->value)) {
            $paginator->appends('category', $this->value);
        }
    }
}
